package view;

import java.awt.Color;
import java.awt.Frame;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.commons.io.FileUtils;


/**
 *
 * @author oem
 */
public class Tela_Inicial extends javax.swing.JFrame {

    private Frame Tela_Inicial;

    /**
     * Creates new form Tela_Inicial
     */
    public Tela_Inicial() {
       Color minhaCor = new Color(100, 100, 100);
        getContentPane().setBackground(minhaCor);
        ImageIcon icon = new ImageIcon("/home/aluno/Área de Trabalho/Filipe/TrabalhoPS_2/logo.png");
        //Mostra_Logo.setIcon(icon);
        //Tela_Inicial.getContentPane().setBackground(Color.black);
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        JPanel_ini = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Cod_Read_JText = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        Cod_generated_JText = new javax.swing.JTextArea();
        jToolBar1 = new javax.swing.JToolBar();
        abrir_file_jb = new javax.swing.JButton();
        TabelaDeRegistradores = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Reg_jTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(123, 123, 123));

        jTabbedPane1.setBackground(new java.awt.Color(123, 123, 123));
        jTabbedPane1.setForeground(new java.awt.Color(177, 177, 177));
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        JPanel_ini.setBackground(new java.awt.Color(100, 100, 100));

        jScrollPane3.setBackground(new java.awt.Color(123, 123, 123));

        Cod_Read_JText.setEditable(false);
        Cod_Read_JText.setBackground(new java.awt.Color(76, 76, 76));
        Cod_Read_JText.setColumns(20);
        Cod_Read_JText.setRows(5);
        jScrollPane3.setViewportView(Cod_Read_JText);

        Cod_generated_JText.setEditable(false);
        Cod_generated_JText.setBackground(new java.awt.Color(76, 76, 76));
        Cod_generated_JText.setColumns(20);
        Cod_generated_JText.setRows(5);
        jScrollPane1.setViewportView(Cod_generated_JText);

        javax.swing.GroupLayout JPanel_iniLayout = new javax.swing.GroupLayout(JPanel_ini);
        JPanel_ini.setLayout(JPanel_iniLayout);
        JPanel_iniLayout.setHorizontalGroup(
            JPanel_iniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 793, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 793, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        JPanel_iniLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane1, jScrollPane3});

        JPanel_iniLayout.setVerticalGroup(
            JPanel_iniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel_iniLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JPanel_iniLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jScrollPane1, jScrollPane3});

        jTabbedPane1.addTab("Inicio", JPanel_ini);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        abrir_file_jb.setBackground(new java.awt.Color(123, 123, 123));
        abrir_file_jb.setForeground(new java.awt.Color(177, 177, 177));
        abrir_file_jb.setText("Abrir Arquivo");
        abrir_file_jb.setFocusable(false);
        abrir_file_jb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        abrir_file_jb.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        abrir_file_jb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrir_file_jbActionPerformed(evt);
            }
        });
        jToolBar1.add(abrir_file_jb);

        TabelaDeRegistradores.setBackground(new java.awt.Color(123, 123, 123));
        TabelaDeRegistradores.setForeground(new java.awt.Color(177, 177, 177));

        jScrollPane2.setBackground(new java.awt.Color(123, 123, 123));
        jScrollPane2.setForeground(new java.awt.Color(177, 177, 177));

        Reg_jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Number", "Value"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Reg_jTable.setSelectionBackground(new java.awt.Color(123, 123, 123));
        Reg_jTable.setSelectionForeground(new java.awt.Color(123, 123, 123));
        jScrollPane2.setViewportView(Reg_jTable);
        if (Reg_jTable.getColumnModel().getColumnCount() > 0) {
            Reg_jTable.getColumnModel().getColumn(0).setResizable(false);
            Reg_jTable.getColumnModel().getColumn(0).setHeaderValue("Name");
            Reg_jTable.getColumnModel().getColumn(1).setResizable(false);
            Reg_jTable.getColumnModel().getColumn(1).setHeaderValue("Number");
            Reg_jTable.getColumnModel().getColumn(2).setResizable(false);
            Reg_jTable.getColumnModel().getColumn(2).setHeaderValue("Value");
        }

        javax.swing.GroupLayout TabelaDeRegistradoresLayout = new javax.swing.GroupLayout(TabelaDeRegistradores);
        TabelaDeRegistradores.setLayout(TabelaDeRegistradoresLayout);
        TabelaDeRegistradoresLayout.setHorizontalGroup(
            TabelaDeRegistradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabelaDeRegistradoresLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TabelaDeRegistradoresLayout.setVerticalGroup(
            TabelaDeRegistradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TabelaDeRegistradoresLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(332, 332, 332))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 801, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TabelaDeRegistradores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(0, 679, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(TabelaDeRegistradores, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(596, 596, 596))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abrir_file_jbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrir_file_jbActionPerformed
        
        JFileChooser fileChooser = new JFileChooser();                                  // cria um objeto para abrir o arquivo
        fileChooser.setDialogTitle ("Selecione o Arquivo TXT a Ser Aberto");            // titulo da caixa de seleção de arquivo
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);                      // set para apenas arquivos
        FileNameExtensionFilter filter = new FileNameExtensionFilter ("Binary","bin");   // configura o tipo de arquivo para aceitar apenas txt
        fileChooser.setFileFilter(filter);                                              // aplica o filtro.
        fileChooser.showOpenDialog(this);
        File arq = fileChooser.getSelectedFile();                                 // pega o arquivo selecionado 
            
             if (arq == null){
                 JDialog aviso = new JDialog (Tela_Inicial, true);
                 aviso.add (new JLabel ("Arquivo invalido ou vazio"));
                 aviso.setVisible(true);
             }
         
          String conteudo ="";
        try {
            conteudo = FileUtils.readFileToString(arq);
        } catch (IOException ex) {
            Logger.getLogger(Tela_Inicial.class.getName()).log(Level.SEVERE, null, ex);
        }
          Cod_Read_JText.setText(conteudo);
          JLabel file_name = new JLabel(arq.getName());
          JPanel_ini.setName("teste");
          
          
    }//GEN-LAST:event_abrir_file_jbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Inicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Cod_Read_JText;
    private javax.swing.JTextArea Cod_generated_JText;
    private javax.swing.JPanel JPanel_ini;
    private javax.swing.JTable Reg_jTable;
    private javax.swing.JPanel TabelaDeRegistradores;
    private javax.swing.JButton abrir_file_jb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
/*>>>>>>> 392493fa2d57565bae06362176e9f25f26b76064*/
